#!/usr/bin/env ruby
require 'zip'
require 'fileutils'

EXTENSION_NAME = 'mcp_for_sketchup'
VERSION = '0.3.0'

# Parse --variant=warehouse|github (default: warehouse).
variant_arg = ARGV.find { |a| a.start_with?('--variant=') }
VARIANT = variant_arg ? variant_arg.split('=', 2).last : 'warehouse'
unless %w[warehouse github].include?(VARIANT)
  abort "invalid --variant '#{VARIANT}'; expected 'warehouse' or 'github'"
end

EVAL_DEFAULT = (VARIANT == 'github')
OUTPUT_NAME  = "#{EXTENSION_NAME}_v#{VERSION}-#{VARIANT}.rbz"

# 1. Generate the autogenerated build_profile.rb inside the extension subfolder.
# Iter-1 CRITICAL-6 + iter-2 CRITICAL-4: wrap File.write AND staging + zip
# in begin/ensure so any mid-build crash (out-of-space mid-File.write,
# signal, zip exception) cleans up the gitignored build_profile.rb. The
# previous draft computed File.write before the begin block — a partial
# write from a disk-full or perms failure would leak the file.
build_profile_path = File.join(EXTENSION_NAME, 'core', 'build_profile.rb')
temp_dir = "#{EXTENSION_NAME}_temp"
begin
  File.write(build_profile_path, <<~RUBY)
    # AUTOGENERATED by package.rb — do not edit. Regenerated per build.
    # Defines the per-variant eval-enabled default baked into each .rbz.
    module MCPforSketchUp
      module Core
        module BuildProfile
          VARIANT                 = #{VARIANT.inspect}.freeze
          EVAL_ENABLED_BY_DEFAULT = #{EVAL_DEFAULT}
        end
      end
    end
  RUBY
  puts "Generated #{build_profile_path}: VARIANT=#{VARIANT}, EVAL_ENABLED_BY_DEFAULT=#{EVAL_DEFAULT}"

  # 2. Prepare a temp staging directory.
  FileUtils.rm_rf(temp_dir) if Dir.exist?(temp_dir)
  FileUtils.mkdir_p(temp_dir)

  # .rbz must contain exactly one root .rb (the loader) + a same-named
  # directory (the extension subfolder); the Trimble signing service rejects
  # anything else at root with "Extra files found." extension.json lives at the
  # TOP of the source tree (sibling of the loader + subfolder) and is
  # intentionally NOT staged into the .rbz — the loader declares the extension
  # metadata via Sketchup::Extension.new. (Source-side extension.json fields are
  # guarded by test/test_extension_json.rb.)
  FileUtils.cp_r(EXTENSION_NAME, temp_dir)
  FileUtils.cp("#{EXTENSION_NAME}.rb", temp_dir)

  # 3. Zip everything into the .rbz file. Wrap the zip in begin/rescue so a
  # crash MID-archive (disk full, I/O error) can't leave a partial/corrupt .rbz:
  # the outer `ensure` below cleans temp_dir + build_profile.rb but NOT
  # OUTPUT_NAME, and a leftover partial artifact could be shipped by a release
  # glob (gh release upload mcp_for_sketchup/*.rbz). Same leak-proof discipline
  # as the post-build verification rescue. rm_f only ever targets THIS build's
  # partial output — the line above already removed any prior .rbz.
  FileUtils.rm(OUTPUT_NAME) if File.exist?(OUTPUT_NAME)
  begin
    Zip::File.open(OUTPUT_NAME, create: true) do |zipfile|
      Dir["#{temp_dir}/**/**"].each do |file|
        next if File.directory?(file)
        puts "Adding: #{file}"
        zipfile.add(file.sub("#{temp_dir}/", ''), file)
      end
    end
  rescue
    FileUtils.rm_f(OUTPUT_NAME)
    raise
  end
ensure
  # 4. Clean up — always runs, even on failure.
  FileUtils.rm_rf(temp_dir) if Dir.exist?(temp_dir)
  FileUtils.rm_f(build_profile_path)
end

# 5. Post-build verification (controller+user-approved Option A — replaces the
# plan's extension.json read, which always raised because extension.json does
# NOT ship in the .rbz; it lives at the top of the source tree as a sibling of
# the loader + subfolder and is intentionally never staged). What DOES ship and
# carries the v0.1.0-rejected identity is the LOADER. Source-side extension.json
# fields stay guarded by test/test_extension_json.rb (Task 4).
#
# A failed assertion here deletes OUTPUT_NAME before re-raising: the .rbz is
# complete but FAILED verification, so it must not survive for a release glob
# (e.g. `gh release upload mcp_for_sketchup/*.rbz`) to pick up — same leak-proof
# discipline as the build_profile.rb cleanup above.
begin
  Zip::File.open(OUTPUT_NAME) do |zf|
    # (a) The variant contract — the whole point of this task.
    # NOTE: the column padding in the substring matches below must stay in sync
    # with the heredoc that generates build_profile.rb above; re-aligning the
    # heredoc without updating these strings would silently break the match.
    bp = zf.find_entry(File.join(EXTENSION_NAME, "core", "build_profile.rb"))
    raise "post-build: build_profile.rb missing from #{OUTPUT_NAME}" unless bp
    bp_body = bp.get_input_stream.read
    unless bp_body.include?("VARIANT                 = #{VARIANT.inspect}")
      raise "post-build: build_profile VARIANT mismatch — expected #{VARIANT.inspect} in #{OUTPUT_NAME}"
    end
    unless bp_body.include?("EVAL_ENABLED_BY_DEFAULT = #{EVAL_DEFAULT}")
      raise "post-build: build_profile EVAL_ENABLED_BY_DEFAULT mismatch — expected #{EVAL_DEFAULT} in #{OUTPUT_NAME}"
    end

    # (b) iter-2 CRITICAL-8 name-regression guard, pointed at the RIGHT artifact:
    # the loader (mcp_for_sketchup.rb), which shipped and caused the v0.1.0 reject.
    loader = zf.find_entry("#{EXTENSION_NAME}.rb")
    raise "post-build: loader #{EXTENSION_NAME}.rb missing from #{OUTPUT_NAME}" unless loader
    loader_body = loader.get_input_stream.read
    unless loader_body.include?("'MCP Server for SketchUp'")
      raise "post-build: loader display name mismatch — expected 'MCP Server for SketchUp' in #{OUTPUT_NAME}"
    end
    unless loader_body =~ /ext\.version\s*=\s*'#{Regexp.escape(VERSION)}'/
      raise "post-build: loader version mismatch — expected #{VERSION} in #{OUTPUT_NAME}"
    end
    puts "post-build verified: VARIANT=#{VARIANT}, EVAL_ENABLED_BY_DEFAULT=#{EVAL_DEFAULT}, loader name + version OK"
  end
rescue
  FileUtils.rm_f(OUTPUT_NAME)
  raise
end

puts "Created #{OUTPUT_NAME} (variant=#{VARIANT}, eval_default=#{EVAL_DEFAULT})"
